config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  devise_for :users

  resources :workers
  resources :charges
  resources :units
  resources :divisions
  resources :teams

  devise_scope :user do
    authenticated :user do
      root 'workers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/views/assets/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">Sistema Funcionarios</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <%= link_to 'Inicio', workers_path, class: "nav-link"  %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Configuración
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Ver cargos', charges_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Ver unidades', units_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Ver divisiones', divisions_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Ver funcionarios', workers_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>