config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  devise_for :users

  resources :workers
  resources :charges
  resources :units
  resources :divisions
  resources :teams

  devise_scope :user do
    authenticated :user do
      root 'workers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :division
  belongs_to :unit
  belongs_to :charge

  validates :avatar, presence: true
  validates :name, presence: true
  validates :phone, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @workers = Worker.all
  end

  def show
  end

  def new
    @worker = Worker.new
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Funcionario creado correctamente.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Funcionario actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Funcionario eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:name, :email, :phone, :division_id, :unit_id, :charge_id, :avatar)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= simple_form_for(@worker) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-12">
        <%= f.association :division, label: 'División', include_blank: false %>
        <%= link_to 'Agregar Otra División', new_division_path, class: 'btn btn-info'  %>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <%= f.association :unit, label: 'Unidad', include_blank: false %>
        <%= link_to 'Agregar Otra Unidad', new_unit_path, class: 'btn btn-info' %>
      </div>
      <div class="col-md-6">
        <%= f.association :charge, label: 'Cargo', include_blank: false %>
        <%= link_to 'Agregar Otro Cargo', new_charge_path, class: 'btn btn-info' %>
      </div>
    </div>
    <hr>
    <% if f.object.avatar? %>
      <div class="row">
        <div class="col-md-4">
          <div class="card" style="width: 20rem;">
            <%= image_tag f.object.avatar.url, style: "width: 19,5rem;", class: 'card-img-top' %>
            <div class="card-body text-center">
              <p class="card-text">
                <strong><%= @worker.name %></strong>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <%= f.input :name, label: 'Nombre' %>
          <%= f.input :email, label: 'Correo Electronico' %>
          <%= f.input :phone, label: 'Anexo Telefonico' %>
          <%= f.input :avatar, label: 'Foto Funcionario' %>
        </div>
      </div>
    <hr>
    <% else %>
      <%= f.input :name, label: 'Nombre' %>
      <%= f.input :email, label: 'Correo Electronico' %>
      <%= f.input :phone, label: 'Anexo Telefonico' %>
      <%= f.input :avatar, label: 'Foto Funcionario' %>
      <hr>
    <% end %>
  </div>
  <div class="form-actions">
    <div class="row">
      <div class="col-md-6">
        <%= f.button :submit, class: 'btn btn-primary btn-block' %>
      </div>
      <div class="col-md-6">
        <%= link_to 'Cancelar', workers_path, class: 'btn btn-danger btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h3>Editar Datos Funcionario</h3>
<hr>
<%= render 'form', worker: @worker %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <h3>Funcionarios</h3>
  </div>
  <div class="col-md-6">
    <p class="text-right">
      <% if user_signed_in? %>
        <%= link_to 'Agregar Nuevo Funcionario', new_worker_path, class: 'btn btn-primary' %>
      <% end %>
    </p>
  </div>
</div>
<hr>
<table class="table table-bordered" id="dttb">
  <thead>
    <tr class="text-center">
      <th>Foto Funcionario</th>
      <th>Nombre Funcionario</th>
      <th>Cargo</th>
      <th>Unidad</th>
      <th>División</th>
      <% if user_signed_in? %>
        <th>Opciones</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr class="text-center">
        <td>
          <%= image_tag worker.avatar_url, width: '40%' if worker.avatar.present? %>
        </td>
        <td><%= worker.name %></td>
        <td><%= worker.charge.name %></td>
        <td><%= worker.unit.name %></td>
        <td><%= worker.division.name %></td>
        <% if user_signed_in? %>
          <td>
            <div class="list-inline">
              <%= link_to 'Ver', edit_worker_path(worker), class: 'btn btn-primary' %>
              <%= link_to 'Eliminar', worker, method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-primary' %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workers/new.html.erb
<h1>Nuevo Funcionario</h1>
<hr>
<%= render 'form', worker: @worker %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Funcionario</h3>
<hr>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <%= image_tag @worker.avatar.url, class: 'card-img-top' %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <h5 class="card-header">Datos Funcionario</h5>
      <div class="card-body">
        <p class="card-text"><strong>Nombre: </strong><%= @worker.name %></p>
        <p class="card-text"><strong>Cargo: </strong><%= @worker.charge.name %> <%= @worker.unit.name %></p>
        <p class="card-text"><strong>División: </strong><%= @worker.division.name %></p>
      </div>
      <div class="card-footer">
        <div class="list-inline">
          <%= link_to 'Editar Funcionario', edit_worker_path(@worker), class: 'btn btn-primary' %>
          <%= link_to 'Volver', workers_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>