config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  devise_for :users

  resources :workers
  resources :charges
  resources :units
  resources :divisions
  resources :teams

  devise_scope :user do
    authenticated :user do
      root 'workers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :workers

  validates :name, presence: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all.order("created_at ASC")
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unidad creada correctamente.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unidad actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unidad eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for(@unit) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nombre" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Cancelar', units_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editar Datos de Unidad</h1>
<hr>
<%= render 'form', unit: @unit %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <h3>Unidades</h3>
  </div>
  <div class="col-md-6">
    <p class="text-right">
      <%= link_to 'Agregar Nueva Unidad', new_unit_path, class: 'btn btn-primary' %>
    </p>
  </div>
</div>
<hr>
<table class="table table-bordered" id="dttb2">
  <thead>
    <tr>
      <th class="text-center">Nombre Unidad</th>
      <th class="text-center">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td class="text-center"><%= unit.name %></td>
        <td class="text-center">
          <%= link_to 'Ver Unidad', edit_unit_path(unit), class: 'btn btn-info btn-sm' %>
          <%= link_to 'Eliminar', unit, method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-danger btn-sm' %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/units/new.html.erb
<h1>Nueva Unidad</h1>
<hr>
<%= render 'form', unit: @unit %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <h5 class="card-header">Datos Unidad</h5>
  <div class="card-body">
      <strong>Nombre:</strong>
      <%= @unit.name %>
  </div>
  <div class="card-footer">
    <div class="list-inline">
      <%= link_to 'Editar Unidad', edit_unit_path(@unit), class: 'btn btn-primary' %>
      <%= link_to 'Volver', units_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>