config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  devise_for :users

  resources :workers
  resources :charges
  resources :units
  resources :divisions
  resources :teams

  devise_scope :user do
    authenticated :user do
      root 'workers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/charge.rb
class Charge < ApplicationRecord
  has_many :workers

  validates :name, presence: true
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all.order("created_at ASC")
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Cargo creado correctamente.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Cargo actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Cargo eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:name)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= simple_form_for(@charge) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Nombre' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Cancelar', charges_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editar Datos del Cargo</h1>

<%= render 'form', charge: @charge %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <h3>Cargos</h3>
  </div>
  <div class="col-md-6">
    <p class="text-right">
      <%= link_to 'Agregar Nuevo Cargo', new_charge_path, class: 'btn btn-primary' %>
    </p>
  </div>
</div>
<hr>
<table class="table table-bordered" id="dttb4">
  <thead>
    <tr>
      <th class="text-center">Nombre Cargo</th>
      <th class="text-center">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td class="text-center"><%= charge.name %></td>
        <td class="text-center">
          <%= link_to 'Ver Cargo', edit_charge_path(charge), class: 'btn btn-info btn-sm' %>
          <%= link_to 'Eliminar', charge, method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/charges/new.html.erb
<h1>Nuevo Cargo</h1>
<hr>
<%= render 'form', charge: @charge %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <h5 class="card-header">
    Datos Cargo
  </h5>
  <div class="card-body">
    <strong>Nombre Cargo:</strong>
    <%= @charge.name %>
  </div>
  <div class="card-footer">
    <div class="list-inline">
      <%= link_to 'Editar Cargo', edit_charge_path(@charge), class: 'btn btn-primary' %>
      <%= link_to 'Volver', charges_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>